name:                H-Ray
version:             0.1.0.0
github:              "marsermd/H-Ray"
license:             MIT
author:              "Michael @marsermd Panin"
maintainer:          "mischapanin@gmail.com"
copyright:           "2018 Michael Panin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/marsermd/H-Ray#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- linear
- containers

library:
  source-dirs: src

executables:
  H-Ray-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - H-Ray

tests:
  H-Ray-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - H-Ray
